### PR TITLE
Release 3.1

### PR DESCRIPTION
**Pull request by wcarthur**

### CODE REVIEW

**Review by NMoghaddam — CHANGES_REQUESTED** [review]
- four input datasets
- Separate the paragraph in landcover after "In order to .." move 2021 earlier in this statement. also, change meshblock to mesh block
- remove "or meshblock" in the mesh blocks part 
- lower case mesh block in settlements and remove - for preprocessing 
- *.img format and release not releases 
 Configuration :
 - replace "The following options need to be set in the configuration file:" with the following options
 - put space in "raster layers-set"
 - change the "In pre_processing step will produce merged meshblock with settlment "
 - "pre_processing step" and " with LCCCS dataset "typoes
 - Place space for the next paragraph between these two sentences: "given topography file. There are two required" 
 - Following to run .... use the space similar to the previous template and keep the space 
 - This script python rasterize.py should be replaced with "To run this script ..."

**Comment by NMoghaddam** [comment]
The requested changes are now implemented and "release 3.1 is good for merging. @wcarthur I tried to merge but wasn't able to. Would you mind checking whether it is restricted?

**Review by wcarthur — COMMENTED** [review]
All reviewed

**Review by NMoghaddam — APPROVED** [review]
Ready for merging

**Pull request merged**
